{% set data= load_setup_py_data() %}
package:
  name: "ts-astrosky-model"
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

test:
  requires:
    - ts-conda-build =0.4
    - astropy
    - palpy
    - rubin-scheduler
    - ts-dateloc
  source_files:
    - python
    - tests
    - pyproject.toml
  commands:
    - scheduler_download_data --update
    - pytest -vs

requirements:
  host:
    - python {{ python }}
    - pip
    - setuptools_scm
    - setuptools
  build:
    - python {{ python }}
    - setuptools_scm
    - setuptools
    - ts-conda-build =0.4
  run:
    - python {{ python }}
    - setuptools
    - setuptools_scm
    - astropy =6
    - palpy
    - rubin-scheduler
    - ts-dateloc
